apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    name: gop-fileserver
spec:
  containers:
  - name: gop-fileserver
    image: kodekloud/fileserver
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  selector:
    app: gop-fileserver
  ports:
  - port: 31200
    targetPort: 8080
