apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    name: gop-fileserver
spec:
  containers:
  - name: gop-fileserver
    image: kodekloud/fileserver
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: data-store
        mountPath: /web
    ports:
      - containerPort: 8080
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  type: NodePort
  selector:
    app: gop-fileserver
  ports:
  - port: 8080
    nodePort: 31200
    targetPort: 8080