apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  labels:
    name: run=jekyll
  namespace: development
spec:
  initContainers:
    - name: copy-jekyll-site
      image: kodekloud/jekyll
      command: ["jekyll", "new", "/site"]
      volumeMounts:
        - name: site
          mountPath: /site
  containers:
  - name: jekyll
    image: kodekloud/jekyll-serve
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 4000
    volumeMounts:
      - name: site
        mountPath: /site
    
  volumes:
    - name: site
      persistentVolumeClaim:
        claimName: jekyll-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: jekyll
spec:
  selector:
    app: jekyll
  type: NodePort
  ports:
  - port: 8080
    targetPort: 4000
    nodePort: 30097
